@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.enginecrafter77.imhotepmc;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
