@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.enginecrafter77.imhotepmc.blueprint;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
